import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { stringify } from 'yaml';
import { buildOpenApi } from '../src/openapi';

const out = resolve(import.meta.dirname, '../../../specs/003-inbox-home/contracts/openapi.yaml');
writeFileSync(
  out,
  '# GENERATED by `pnpm -F @cdevi/contracts openapi` from packages/contracts/src — do not edit by hand.\n' +
    stringify(buildOpenApi(), { lineWidth: 0 }),
);
console.log(`wrote ${out}`);
