import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { stringify } from 'yaml';
import { buildOpenApi, buildWorkflowDetailOpenApi } from '../src/openapi';

const HEADER =
  '# GENERATED by `pnpm -F @cdevi/contracts openapi` from packages/contracts/src — do not edit by hand.\n';

const targets: Array<[path: string, doc: () => Record<string, unknown>]> = [
  ['../../../specs/003-inbox-home/contracts/openapi.yaml', buildOpenApi],
  ['../../../specs/001-sdlc-control-plane-mvp/contracts/openapi.yaml', buildWorkflowDetailOpenApi],
];

for (const [rel, build] of targets) {
  const out = resolve(import.meta.dirname, rel);
  writeFileSync(out, HEADER + stringify(build(), { lineWidth: 0 }));
  console.log(`wrote ${out}`);
}
