// GENERATED from tokens/tokens.json by scripts/build-tokens.mjs — do not edit.
export const tokenVersion = '1.1.0';

/** Token path → CSS custom property name. */
export const cssVar = {
  'color.canvas': '--canvas',
  'color.surface': '--surface',
  'color.surface-2': '--surface-2',
  'color.ink': '--ink',
  'color.ink-2': '--ink-2',
  'color.ink-3': '--ink-3',
  'color.line': '--line',
  'color.line-2': '--line-2',
  'color.line-strong': '--line-strong',
  'color.saffron': '--saffron',
  'color.saffron-soft': '--saffron-soft',
  'color.saffron-ink': '--saffron-ink',
  'color.saffron-strong': '--saffron-strong',
  'color.indigo': '--indigo',
  'color.indigo-soft': '--indigo-soft',
  'color.green': '--green',
  'color.green-soft': '--green-soft',
  'color.red': '--red',
  'color.red-soft': '--red-soft',
  'color.code-bg': '--code-bg',
  'color.code-ink': '--code-ink',
  'color.code-read': '--code-read',
  'color.code-write': '--code-write',
  'color.code-ok': '--code-ok',
  'color.code-err': '--code-err',
  'color.code-dim': '--code-dim',
  'font.ui': '--ui',
  'font.mono': '--mono',
  'font.sinhala': '--sinhala',
  'radius.md': '--r',
  'radius.lg': '--r-lg',
  'radius.pill': '--radius-pill',
  'space.1': '--space-1',
  'space.2': '--space-2',
  'space.3': '--space-3',
  'space.4': '--space-4',
  'space.5': '--space-5',
  'space.6': '--space-6',
  'space.8': '--space-8',
  'text.xs': '--text-xs',
  'text.sm': '--text-sm',
  'text.base': '--text-base',
  'text.lg': '--text-lg',
  'text.xl': '--text-xl',
  'text.2xl': '--text-2xl',
  'shadow.1': '--shadow-1',
} as const;

export type TokenName = keyof typeof cssVar;

/** Semantic alias → base colour token path. */
export const semanticColor = {
  'needs-you': 'color.saffron',
  'primary-action': 'color.saffron',
  'running': 'color.indigo',
  'verified': 'color.green',
  'failed': 'color.red',
  'evidence': 'color.green',
  'state.queued': 'color.ink-2',
  'state.running': 'color.indigo',
  'state.waiting': 'color.saffron-ink',
  'state.waiting-for-human': 'color.saffron',
  'state.blocked': 'color.red',
  'state.failed': 'color.red',
  'state.retrying': 'color.indigo',
  'state.completed': 'color.green',
  'state.cancelled': 'color.ink-3',
  'risk.low': 'color.ink-2',
  'risk.medium': 'color.indigo',
  'risk.high': 'color.saffron-ink',
  'risk.critical': 'color.saffron-strong',
} as const;
