// Concatenates the CSS layers into css/cdevi.css. GENERATED output — do not edit cdevi.css by hand.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const layers = ['tokens.css', 'fonts.css', 'base.css', 'components.css'];

export function buildCssBundle() {
  const parts = layers.map((f) => readFileSync(resolve(root, 'css', f), 'utf8').trimEnd());
  // @import rules must precede all other rules: hoist them from fonts.css to the top of the bundle.
  const imports = [];
  const bodies = parts.map((css) =>
    css.replace(/^@import[^;]+;\s*$/gm, (m) => {
      imports.push(m.trim());
      return '';
    }),
  );
  return (
    '/* GENERATED by scripts/build-css.mjs from css/{' +
    layers.join(',') +
    '} — do not edit. */\n' +
    imports.join('\n') +
    '\n\n' +
    bodies.map((b) => b.trim()).join('\n\n') +
    '\n'
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const out = resolve(root, 'css/cdevi.css');
  writeFileSync(out, buildCssBundle());
  console.log(`wrote ${out}`);
}
